- name: Practice makes man perfect
  hosts: local
  connection: local
  vars:
    time: two
  
  tasks:
  - name: Daily Practice
    ansible.builtin.debug:
      msg: "{{ time }} hour maximum"
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Start nginx
    ansible.builtin.service:
      name: nginx
      state: started    
      enabled: yes
  vars_prompt:    
    - name: vars_prompt
      prompt: "please enter your name"
      private: false
    
    - name: print prompt details
      ansible.builtin.debug:
        msg: "{{ vars_prompt }}"
        