- name: Practice makes man perfect
  hosts: local
  connection: local
  vars:
    time: two
  tasks:
  # - name: Daily Practice
  #   ansible.builtin.debug:
  #     msg: "{{ time }} hour maximum"
  - name: install nginx
    ansible.builtin.package:
    - name: nginx
      state: present   